nixos/cnping: specify new wrapper options to unbreak
It seems `security.wrappers` now requires `{owner,group}` to be
specified:

   error: The option `security.wrappers.cnping.owner' is used but not defined.
   (use '--show-trace' to show detailed location information)